### ISSUE TITLE
Breaking API changes without using versioning

### ISSUE THREAD

**Issue by edwardsph** [ChurchSuite/churchsuite-api#10]
I really appreciate the efforts to improve and document the API but just want to point out that there has been another change which is not backwards compatible and breaks current integrations. You have split custom fields into 2 parts (as per your new documentation). The API has the concept of versioning built in yet you have not used this to help customers manage these changes. Can I suggest that if your changes are going to break the API you keep v1 functioning (but deprecated) whilst implementing the changes in v2.
Thanks, Pete

**Comment by jeremyscode** [comment]
@edwardsph the groups custom fields were being sent over incorrectly so this is why it had to change, it was in essence a bug fix but I apologise for the inconvenience. We may move to a v2 of the API but this is as yet not on our current roadmap. Thanks!
