### ISSUE TITLE
OpenAPI specification

### ISSUE THREAD

**Issue by rickbutterfield** [ChurchSuite/churchsuite-api#13]
Is there any chance of getting an OpenAPI/Swagger spec for the API? Would be useful to be able to autogenerate clients for C# projects.

https://github.com/OAI/OpenAPI-Specification

**Comment by jeremyscode** [comment]
@rickbutterfield sorry again for the delay. We don't have any plans for this at the moment, but if we do decide to make a big change to our API we will;
1. do it under a new version
2. make sure that we let our customers know, particularly those already using our current API

Thanks!
