### ISSUE TITLE
JSON not showing sequences of events if `featured` is set to 1

### ISSUE THREAD

**Issue by rickbutterfield** [ChurchSuite/churchsuite-api#14]
If I request the JSON from https://valley.churchsuite.co.uk/embed/calendar/json?featured=0, I can see 23 results when searching for "Prayer Meeting".

If I try the same request but with featured set to 1 (https://valley.churchsuite.co.uk/embed/calendar/json?featured=1) I can only see 2, the first two of the sequence.

I understand this is intended functionality, but it would be nice to have a flag to change this like `group_by_sequence` in the API calls.

**Comment by jeremyscode** [comment]
Hi @rickbutterfield - sorry for the delay in getting back to you! I'm afraid we don't have any plans to make any changes to the JSON feeds at this time. I would recommend that you consider using the API instead.
