### ISSUE TITLE
API returning 500

### ISSUE THREAD

**Issue by nanorepublica** [ChurchSuite/churchsuite-api#15]
I am trying to hit the API this morning and I am currently getting a 500 status code back. I am contacting support as well, but thought this would be an appropriate place as well.

I am trying to get a list of tags for my church.

**Comment by gjcourtney** [comment]
You're requesting a bad URL - your request is to v1/v1/addressbook/tags - you've repeated v1 twice. If you fix that then you should get what you're expecting.

**Comment by nanorepublica** [comment]
Thanks for the very swift response, although I feel this ought to be returning a 400 which correctly denotes that I the client had done something wrong rather than a 500 while denotes the server has done something wrong.
