### ISSUE TITLE
Get Small Group clusters not returning all data

### ISSUE THREAD

**Issue by nanorepublica** [ChurchSuite/churchsuite-api#16]
Hi there, 

I have am attempting to grab information for a specific cluster including the groups associated with it using this URL: `https://api.churchsuite.co.uk/v1/smallgroups/cluster/20?groups=true`

However I am only getting back the following data:
```{'id': '20', 'name': 'Breathe Ministry', 'no_groups': '5'}```

What am I doing wrong?

**Comment by jeremyscode** [comment]
Hi, sorry about that - we're slowly trying to update our API and clearly forgot to update the documentation in this instance. Instead please use the following endpoint in order to get the groups for a cluster:
`https://api.churchsuite.co.uk/v1/smallgroups/groups?cluster_id=20`
