### ISSUE TITLE
date_start Calendar query param not working as expected

### ISSUE THREAD

**Issue by dhulme** [ChurchSuite/churchsuite-api#17]
Hi,

On the Calendar module I've noticed that the `date_start` query string parameter is not working as expected. It should filter by date, but doesn't seem to be. It works if I use `datetime_start` though. I think this may have broken recently as I think it used to work! Perhaps the docs just need updating https://github.com/ChurchSuite/churchsuite-api/blob/master/modules/calendar.md.

Thanks

![image](https://user-images.githubusercontent.com/1234671/99907174-30009c00-2cd3-11eb-8bf1-bb684c40f826.png)

**Comment by jeremyscode** [comment]
Hi David, we've corrected this mistake. You should now be able to use the date_start and date_end parameters as usual. Thanks!
