### ISSUE TITLE
Small groups JSON feed shows `null` tags

### ISSUE THREAD

**Issue by rickbutterfield** [ChurchSuite/churchsuite-api#22]
This must have only happened in the past 24 hours or so, but the feed is returning null for the tags when `show_tags=1`.

URL: https://valley.churchsuite.co.uk/embed/smallgroups/json?view=active_future&show_tags=1

<img width="465" alt="Screenshot 2022-01-10 at 19 04 05" src="https://user-images.githubusercontent.com/200450/148824033-f815dae6-1330-4711-8be5-657ae989a1b0.png">

**Comment by jeremyscode** [comment]
Thanks Rick, this has been fixed now.
