### ISSUE TITLE
Mistake in JSON documentation?

### ISSUE THREAD

**Issue by anchordigi** [ChurchSuite/churchsuite-api#23]
Hi, I think I may have found a mistake in your JSON documentation for the calendar events list. The documentation says to use the paramater 'featured_signup' to filter whether to only show featured events or not. This wasn't working for me, so I just tried using 'featured' instead and that seems to be working.

I might be reading the documentation wrong, but just wanted to flag in case this is a mistake.

**Comment by s-coates** [comment]
Thanks for pointing this out! Yes, that should be 'featured'.

**Comment by anchordigi** [comment]
Hi,

I've now updated my code to use 'featured' but it still doesn't seem to be working correctly. If I use the query string 'featured=1&num_results=9' then I get 6 results returned. However when I use the query string 'featured=1&num_results=0' to get all the featured events I get 15 results returned.

So shouldn't my first attempt with num_results=9 have returned 9 results?

Thanks,
James

**Comment by s-coates** [comment]
Hi James,

Yes it should be returning 9 results. I've just checked and this is working as expected using our demo data. 

I'd be keen to take a deeper look into why that isn't the case with your data. Can you email this query through to ChurchSuite support so we can raise a ticket?

Our support email address is [support@churchsuite.com](mailto:support@churchsuite.com).

Thanks,
Shane
