### ISSUE TITLE
Support `Authorization` header for OAuth

### ISSUE THREAD

**Issue by darbymanning** [ChurchSuite/churchsuite-api#24]
Thought I would create a new issue for this. In a [#21](https://github.com/ChurchSuite/churchsuite-api/issues/21) it was mentioned that there was some consideration to supporting the `Authorization` header for OAuth requests. It would be really beneficial to do this, as it does look like this is the standard approach for OAuth now. We could keep accepting the `X-Auth` header too, so that this is backwards compatible.

FWIW, my main driver for wanting this is that I've been working with Postman, which has a method of making OAuth request through its GUI - but it assumes use of the `Authorization` header.

**Comment by gjcourtney** [comment]
If you give this a go now, you should find that the `Authorization` header is being supported as an alternative to the `X-Auth` header. You'll need to provide the `Authorization` header with the bearer, e.g. `Bearer :token_key`.

Perhaps you could have a try and confirm that it's working for you now?

**Comment by darbymanning** [comment]
Ah great, that's working perfectly, thanks @gjcourtney
