### ISSUE TITLE
Flows endpoints don't show stages

### ISSUE THREAD

**Issue by rickbutterfield** [ChurchSuite/churchsuite-api#25]
The API examples show that querying `/v1/addressbook/flows` should show `stages` as an array but it's not included in my response. Is there a flag that needs to be passed in?

<img width="1295" alt="Screenshot 2022-12-17 at 09 31 16" src="https://user-images.githubusercontent.com/200450/208235537-a096bc1f-08df-47ec-b13b-ad0bd5bcc0fe.png">

**Comment by adnweedon** [comment]
Thanks for raising this, you are correct that the documentation was out of date.

I've updated the documentation to remove the stages from the Flow response, and I've documented the new endpoint that has replaced it (/v1/addressbook/flow_stages/{flow_id}). We're sorry for any inconvenience caused - feel free to get in touch again if you have any more issues!
