### ISSUE TITLE
Rotas API access

### ISSUE THREAD

**Issue by TechWilk** [ChurchSuite/churchsuite-api#28]
I've taken a look around the API but not yet been able to find any documentation of how to access service details. It would be really helpful to have access to this data for signage and to automate mundane tasks around the church, such as uploading sermons to the website.

I'd like to be able to 
- list available services (https://{subdomain}.churchsuite.com/modules/rotas/service_index.php)
- search for or list of dates for each of these services
- and then fetch data about individual services (e.g. data available on: `https://{subdomain}.churchsuite.com/modules/rotas/service_view.php?id={id}`)

Particularly, I'm interested in the following:
- Service name
- Date of service
- Service notes
- Name of people with specific roles in one of the rotas (e.g. preacher)

Longer term, also:
- Service Plan

**Comment by keeneye** [comment]
+1 We're very keen to access this information via the API too.

**Comment by Woody93** [comment]
+1 Also

**Comment by gjcourtney** [comment]
Thanks for your interest in this, this is on our roadmap and we're hoping to release this later in 2023. As you might expect, we have an internal REST API that we use ourselves to access the Rotas data, but there are a number of alterations we want to make to it before it's ready for public access. As a more general principle, we're also working towards a v2 API specification, which would likely follow the Open API standards - it's likely that Rotas API endpoints will be released once this is ready.

This is all very much in our plans and we're hoping it will be available in the coming months. Hope that helps give some insight!

**Comment by Timo6** [comment]
Any update on this 14 months later?

**Comment by tomduckering** [comment]
Just found this - does the "closed" state of this issue mean it's in the works?

**Comment by pelshen** [comment]
It's now 2025 and the last word on this was that you were looking at late 2023, is this still coming or is it no longer a priority?

**Comment by netcarver** [comment]
Autumn 2026: Please could we have access to the rotas via API endpoints. Even something to just list the rotas (GET /rotas/rotas) and a rota by ID (GET /rotas/rotas/{id}) would be very helpful.
