### ISSUE TITLE
Session api

### ISSUE THREAD

**Issue by louis-quaintance** [ChurchSuite/churchsuite-api#29]
It would be great to have an api to record child/person attendance at a session such as a sunday school class, is this on the roadmap?

**Comment by lukesalter** [comment]
Thanks for your interest in this, this is on our roadmap and we're hoping to release this later in 2023. As you might expect, we have an internal REST API that we use ourselves to access the Children data, but there are a number of alterations we want to make to it before it's ready for public access. As a more general principle, we're also working towards a v2 API specification, which would likely follow the Open API standards - it's likely that Children and Session API endpoints will be released once this is ready.

This is all very much in our plans and we're hoping it will be available in the coming months. Hope that helps give some insight!

**Comment by louis-quaintance** [comment]
Thanks
