### ISSUE TITLE
adding keydate

### ISSUE THREAD

**Issue by johnelbourne** [ChurchSuite/churchsuite-api#30]
Any news on when the addressbook and children API modules will support adding keydates?

**Comment by lukesalter** [comment]
Hi John,

We're currently working hard on APIv2 so it's unlikely that APIv1 will be getting any new endpoints any time soon. 

APIv2 will initially cover the functionality of APIv1 initially plus some additional GET endpoints. We'll move on to other CRUD operations later in the year (POST, PUT and DELETE). APIv2 will come with new documentation, stricter standards and a few other more developer friendly features. We're not rushing the API but we will be releasing more and more endpoints incrementally throughout the year.

Thank you for logging your interest in key date resource POST - we'll be sure to bare this in mind as we build out the new endpoints. We plan to reach out to developers like yourself who are currently using the API to get a feel for how it's being used so I imagine we'll be in touch via the mailing list (join here: https://churchsuite.com/api-and-json/) in time.

Luke
