### ISSUE TITLE
Add "category" to tags API calls

### ISSUE THREAD

**Issue by tomduckering** [ChurchSuite/churchsuite-api#31]
Tags in the ChurchSuite UI are assignable to a category however this information is not visible in the API (Per: https://github.com/ChurchSuite/churchsuite-api/blob/master/modules/addressbook.md#get-a-tag)

As an MVP could you please add category to the responses which include tag info?

More "gold plated" version would be to have categories as a first class entity in the API too.

Thanks.

**Comment by adnweedon** [comment]
Hi Tom,

Thanks for getting in touch!

We're in the process of working on a much broader v2 API, which has both Category responses and includes the Category ID on the tag response; as such, we're not currently making any further changes to v1 at this time, but be assured that better things are on the horizon!

Blessings,

Ant

**Comment by tomduckering** [comment]
@adnweedon - any indication as to when you'll be releasing the v2 API? Other issue comments indicate 2023 but we're obviously past that.

**Comment by adnweedon** [comment]
Hi! As you've found, we've had good intentions to improve things for a few years now - we know how frustrating unreliable or poorly documented APIs can be! Over the last year we've put a lot of work into improving lots of things behind the scenes to make a better v2 API possible, and so while we don't have a fixed timescale on it, it is under active development, and much better things are coming!

**Comment by tomduckering** [comment]
No worries. I know how challenging software timelines can be. I'll wait patiently.
