### ISSUE TITLE
Documentation for AddressBook 'tags' API needs updating

### ISSUE THREAD

**Issue by mattss** [ChurchSuite/churchsuite-api#4]
The tag api (/v1/addressbook/tag/1) used to return the number of contacts for a tag under the 'no_contacts' property, as per the docs. It now appears to return the field 'tag_no_contacts' instead.

Was this a deliberate change and, if so, could the documentation be updated?

Many thanks,

**Comment by jeremyscode** [comment]
@mattss sorry for the delay, it should definitely be `no_contacts` (although eventually we'd like to name it `num_contacts`. We're going to push a change soon that will temporarily give both, along with `tag_id` and `id` (it should just be `id`). I will update the documentation once this is live so you should get notified when that happens. Thanks!
