### ISSUE TITLE
Retrieve contacts from the address book with custom fields

### ISSUE THREAD

**Issue by Dreyer** [ChurchSuite/churchsuite-api#5]
Hi @gjcourtney + team,

Is there a way to perform a search for contacts against `custom_fields`?

Let's say I need to return all contacts which have a custom field called 'foo bar' and a value of 'lorem ipsum'.

`GET /v1/addressbook/contacts?custom_fields.name=foo+bar&custom_fields.value=lorem+ipsum`

Maybe there is another way to do this already?

**Comment by jeremyscode** [comment]
Hi @Dreyer, you can filter contacts by using the `customx` parameter, where `x` is the ID of the custom field. For example:
`GET /v1/addressbook/contacts?custom1=foo+bar&custom2=lorem+ipsum`
Hope this helps and sorry for the delay!
