### ISSUE TITLE
spec doesn't seem right for updating tags

### ISSUE THREAD

**Issue by johnelbourne** [ChurchSuite/churchsuite-api#6]
The spec indicates tags can be updated like this:

"tags":[
    {
      "name":"Newcomers"
    },
    {
      "name":"Not in a group"
    }
  ]

But actually the API works with this format instead:

"tags": "Newcomers,Not in a group"

Is the spec wrong or the implementation?

**Comment by jeremyscode** [comment]
@johnelbourne this has been corrected. Whilst you can send it over as a CSV the best way to do it is as a flat array of tag names:
`"tags": ["Newcomes", "Not in a group"]`
